
package VIEW;

import DAO.CategoriaDAO;
import DTO.CategoriaDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Categoria extends javax.swing.JFrame {

    public Categoria() {
        initComponents();
        listarRacas();
        listarServicos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtRaca = new javax.swing.JTextField();
        txtServico = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServicos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRacas = new javax.swing.JTable();
        btnAddRaca = new javax.swing.JButton();
        btnAlterRaca = new javax.swing.JButton();
        btnDelRaca = new javax.swing.JButton();
        btnAddServico = new javax.swing.JButton();
        btnAlterServico = new javax.swing.JButton();
        btnDelServico = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CATEGORIAS");

        jLabel1.setText("Raças");

        jLabel2.setText("Serviços");

        tblServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Serviços Cadastrados"
            }
        ));
        jScrollPane1.setViewportView(tblServicos);

        tblRacas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Raças Cadastradas"
            }
        ));
        jScrollPane2.setViewportView(tblRacas);

        btnAddRaca.setBackground(new java.awt.Color(255, 216, 98));
        btnAddRaca.setForeground(new java.awt.Color(0, 0, 0));
        btnAddRaca.setText("Add Raça");
        btnAddRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRacaActionPerformed(evt);
            }
        });

        btnAlterRaca.setBackground(new java.awt.Color(255, 216, 98));
        btnAlterRaca.setText("Alterar Raça");
        btnAlterRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterRacaActionPerformed(evt);
            }
        });

        btnDelRaca.setBackground(new java.awt.Color(255, 216, 98));
        btnDelRaca.setText("Del Raça");
        btnDelRaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelRacaActionPerformed(evt);
            }
        });

        btnAddServico.setBackground(new java.awt.Color(255, 216, 98));
        btnAddServico.setText("Add Serviço");
        btnAddServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddServicoActionPerformed(evt);
            }
        });

        btnAlterServico.setBackground(new java.awt.Color(255, 216, 98));
        btnAlterServico.setText("Alterar Serviço");
        btnAlterServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterServicoActionPerformed(evt);
            }
        });

        btnDelServico.setBackground(new java.awt.Color(255, 216, 98));
        btnDelServico.setText("Del Serviço");
        btnDelServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelServicoActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(255, 216, 98));
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtRaca))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtServico)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDelRaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddRaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterRaca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(btnListar)
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAlterServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddServico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddRaca)
                    .addComponent(btnAddServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlterRaca)
                    .addComponent(btnAlterServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelRaca)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDelServico)
                        .addComponent(btnListar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int[] ids_racas = new int[100]; 
    int[] ids_servicos = new int[100];
    private void btnAddRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRacaActionPerformed
            adicionarRaca();
            listarRacas();
    }//GEN-LAST:event_btnAddRacaActionPerformed

    private void btnAddServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddServicoActionPerformed
            adicionarServico();
            listarServicos();
    }//GEN-LAST:event_btnAddServicoActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarRacas();
        listarServicos();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAlterServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterServicoActionPerformed
        alterarServico();
        listarServicos();
    }//GEN-LAST:event_btnAlterServicoActionPerformed

    private void btnAlterRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterRacaActionPerformed
        alterarRacas();
        listarRacas();
    }//GEN-LAST:event_btnAlterRacaActionPerformed

    private void btnDelRacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelRacaActionPerformed
        deletaRaca();
        listarRacas();
    }//GEN-LAST:event_btnDelRacaActionPerformed

    private void btnDelServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelServicoActionPerformed
        deletaServico();
        listarServicos();
    }//GEN-LAST:event_btnDelServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRaca;
    private javax.swing.JButton btnAddServico;
    private javax.swing.JButton btnAlterRaca;
    private javax.swing.JButton btnAlterServico;
    private javax.swing.JButton btnDelRaca;
    private javax.swing.JButton btnDelServico;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblRacas;
    private javax.swing.JTable tblServicos;
    private javax.swing.JTextField txtRaca;
    private javax.swing.JTextField txtServico;
    // End of variables declaration//GEN-END:variables
    
    private void adicionarRaca(){
        String raca;
            raca = txtRaca.getText();
            
            CategoriaDTO objcategoriadto = new CategoriaDTO();
            objcategoriadto.setRaca(raca);
            
            CategoriaDAO objcategoriadao = new CategoriaDAO();
            objcategoriadao.cadastrarRaca(objcategoriadto);
    }
    
    private void adicionarServico(){
        String servico;
            servico = txtServico.getText();
            
            CategoriaDTO objcategoriadto = new CategoriaDTO();
            objcategoriadto.setServico(servico);
            
            CategoriaDAO objcategoriadao = new CategoriaDAO();
            objcategoriadao.cadastrarServico(objcategoriadto);
    }
    
    private void listarRacas(){
        try {
            CategoriaDAO objcategoriadao = new CategoriaDAO();
            
            DefaultTableModel model = (DefaultTableModel) tblRacas.getModel();
            model.setNumRows(0);
            
            ArrayList<CategoriaDTO> lista = objcategoriadao.listarRaca();
            
            for(int i = 0; i < lista.size(); i++){
                ids_racas[i] = lista.get(i).getId_raca();
                model.addRow(new Object[]{
                    lista.get(i).getRaca()
                });
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Raças VIEW: "+ erro);
        }
    }
    
    private void listarServicos(){
        try {
            CategoriaDAO objcategoriadao = new CategoriaDAO();
            
            DefaultTableModel model = (DefaultTableModel) tblServicos.getModel();
            model.setNumRows(0);
            
            ArrayList<CategoriaDTO> lista = objcategoriadao.listarServico();
            
            for(int i = 0; i < lista.size(); i++){
                ids_servicos[i] = lista.get(i).getId_servico();
                model.addRow(new Object[]{
                    lista.get(i).getServico()
                });
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Listar Servicos VIEW: "+ erro);
        }
    }
    
    private void alterarRacas(){
        String raca;
        int linha, id_raca;
        
        linha = tblRacas.getSelectedRow();
        id_raca = ids_racas[linha];
        raca = tblRacas.getModel().getValueAt(linha, 0).toString();
        
        CategoriaDTO objcategoriadto = new CategoriaDTO();
        objcategoriadto.setId_raca(id_raca);
        objcategoriadto.setRaca(raca);
        
        CategoriaDAO objcategoriadao = new CategoriaDAO();
        objcategoriadao.alterarRaca(objcategoriadto);
    }
    
    private void alterarServico(){
        int linha, id_servicos;
        String servico;
        
        linha = tblServicos.getSelectedRow();
        id_servicos = ids_servicos[linha];
        servico = tblServicos.getModel().getValueAt(linha, 0).toString();
        
        CategoriaDTO objcategoriadto = new CategoriaDTO();
        objcategoriadto.setId_servico(id_servicos);
        objcategoriadto.setServico(servico);
        
        CategoriaDAO objcategoriadao = new CategoriaDAO();
        objcategoriadao.alterarServico(objcategoriadto);
    }
    
    private void deletaRaca(){
        int id_raca, linha;
        
        linha = tblRacas.getSelectedRow();
        id_raca = ids_racas[linha];
        
        CategoriaDTO objcategoriadto = new CategoriaDTO();
        objcategoriadto.setId_raca(id_raca);
        
        CategoriaDAO objcategoriadao = new CategoriaDAO();
        objcategoriadao.deletaRaca(objcategoriadto);
    }
    
    private void deletaServico(){
        int id_servico, linha;
        
        linha = tblServicos.getSelectedRow();
        id_servico = ids_servicos[linha];
        
        CategoriaDTO objcategoriadto = new CategoriaDTO();
        objcategoriadto.setId_servico(id_servico);
        
        CategoriaDAO objcategoriadao = new CategoriaDAO();
        objcategoriadao.deletaServico(objcategoriadto);
    }
}
