/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.AgendamentoDAO;
import DTO.AgendamentoDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gabriel
 */
public class ListarAgendamento extends javax.swing.JFrame {

    /**
     * Creates new form ListarAgendamento
     */
    public ListarAgendamento() {
        initComponents();
        listarAgendamentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAgendamentos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTelaAgendar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcuir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AGENDAMENTOS");

        tblAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome Pet", "Especie", "Porte", "Peso (Kg)", "Data", "Horário", "Valor (R$)", "Profissional", "Procedimento", "Realizado?"
            }
        ));
        tblAgendamentos.setRowHeight(20);
        jScrollPane1.setViewportView(tblAgendamentos);

        jLabel1.setText("Lista de Agendamentos");

        btnTelaAgendar.setBackground(new java.awt.Color(255, 216, 98));
        btnTelaAgendar.setText("Adicionar");
        btnTelaAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaAgendarActionPerformed(evt);
            }
        });

        btnListar.setBackground(new java.awt.Color(255, 216, 98));
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 216, 98));
        btnAlterar.setText("Editar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcuir.setBackground(new java.awt.Color(255, 216, 98));
        btnExcuir.setText("Excluir");
        btnExcuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcuirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTelaAgendar)
                .addGap(88, 88, 88)
                .addComponent(btnListar)
                .addGap(114, 114, 114)
                .addComponent(btnAlterar)
                .addGap(87, 87, 87)
                .addComponent(btnExcuir)
                .addGap(134, 134, 134))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 697, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTelaAgendar)
                    .addComponent(btnListar)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcuir))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    int[] ids_agendamentos = new int[100];
    
    private void btnTelaAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaAgendarActionPerformed
        Agendamento objagendamento = new Agendamento();
        objagendamento.setVisible(true);
    }//GEN-LAST:event_btnTelaAgendarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        listarAgendamentos();
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        alterarAgendamento();
        listarAgendamentos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcuirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcuirActionPerformed
        deletaAgendamento();
        listarAgendamentos();
    }//GEN-LAST:event_btnExcuirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcuir;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnTelaAgendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAgendamentos;
    // End of variables declaration//GEN-END:variables

    private void listarAgendamentos(){
        try {
            AgendamentoDAO objagendamentodao = new AgendamentoDAO();
            DefaultTableModel model = (DefaultTableModel) tblAgendamentos.getModel();
            model.setNumRows(0);
            
            ArrayList<AgendamentoDTO> lista = objagendamentodao.listarAgendamentos();
            
            for(int i = 0; i < lista.size();i++){
                ids_agendamentos[i] = lista.get(i).getId_agendamento();
                model.addRow(new Object[]{
                    lista.get(i).getNomePet(),
                    lista.get(i).getEspecie(),
                    lista.get(i).getPorte(),
                    lista.get(i).getPeso(),
                    lista.get(i).getData(),
                    lista.get(i).getHorario(),
                    lista.get(i).getValorServico(),
                    lista.get(i).getNomeProfissional(),
                    lista.get(i).getProcediemnto(),
                    lista.get(i).getRealizado(),
                });
            }
            
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarAgendamentos: " + erro);
        }
    }
    
    private void alterarAgendamento(){
        int id_agendamento, linha;
        String nomepet, especie, porte, peso, data, horario, valor, profissional,
                procedimento, realizado;
        
        AgendamentoDTO objagendamentodto = new AgendamentoDTO();
        
        linha = tblAgendamentos.getSelectedRow();
        
        id_agendamento = ids_agendamentos[linha];
        objagendamentodto.setId_agendamento(id_agendamento);
        
        nomepet = tblAgendamentos.getModel().getValueAt(linha, 0).toString();
        objagendamentodto.setNomePet(nomepet);
        
        especie = tblAgendamentos.getModel().getValueAt(linha, 1).toString();
        objagendamentodto.setEspecie(especie);
        
        porte = tblAgendamentos.getModel().getValueAt(linha, 2).toString();
        objagendamentodto.setPorte(porte);
        
        peso = tblAgendamentos.getModel().getValueAt(linha, 3).toString();
        objagendamentodto.setPeso(peso);
        
        data = tblAgendamentos.getModel().getValueAt(linha, 4).toString();
        objagendamentodto.setData(data);
        
        horario = tblAgendamentos.getModel().getValueAt(linha, 5).toString();
        objagendamentodto.setHorario(horario);
        
        valor = tblAgendamentos.getModel().getValueAt(linha, 6).toString();
        objagendamentodto.setValorServico(valor);
        
        profissional = tblAgendamentos.getModel().getValueAt(linha, 7).toString();
        objagendamentodto.setNomeProfissional(profissional);
        
        procedimento = tblAgendamentos.getModel().getValueAt(linha, 8).toString();
        objagendamentodto.setProcediemnto(procedimento);
        
        realizado = tblAgendamentos.getModel().getValueAt(linha, 9).toString();
        objagendamentodto.setRealizado(realizado);
        
        AgendamentoDAO objagendamentodao = new AgendamentoDAO();
        objagendamentodao.alterarAgendamento(objagendamentodto);
    }
    
    private void deletaAgendamento(){
        int linha, id_agendamento;
        String idString;
        
        linha = tblAgendamentos.getSelectedRow();
        
        id_agendamento = ids_agendamentos[linha];
        
        AgendamentoDTO objagendamentodto = new AgendamentoDTO();
        objagendamentodto.setId_agendamento(id_agendamento);
        
        AgendamentoDAO objagendamentodao = new AgendamentoDAO();
        objagendamentodao.deletaAgendamento(objagendamentodto);
    }
}
